openapi: 3.0.1
info:
  title: Fornecedores API
  description: APIs de busca de produtos em fornecedores.
  contact:
    email: bcem@pucminas.br
  version: 1.0.0
externalDocs:
  description: Encontre mais a respeito da API Fornecedores
  url: https://github.com/caiosduarte/aws-montagem-exibicao-catalogo
servers:
- url: https://localhost:8080/catalogo/v1
- url: http://localhost:8080/catalogo/v1
tags:
- name: fornecedores
  description: Busca dos produtos em fornecedores.
components:
  parameters:
    fornecedorId:
      - in: path
        name: fornecedorId
        required: true
        type: integer
        format: int64 
        minimal: 1
      
  schemas:
    Fornecedor:
      type: object
      properties:
        id:
          type: integer
          format: int64
        razaoSocial:
          type: string
        nomeFantasia:
          type: string
        cnpj:
          type: string
        status:
          type: string
          description: Status do Fornecedor
          enum:
          - ativo
          - inativo
        site:
          type: string
      required:
        - id
        - razaoSocial
        - cnpj
    Produto:
      type: object
      properties:
        id:
          type: integer
          description: identificador interno do produto
          format: int64
        referencia:
          type: string
        fornecedorId:
          type: integer
          format: int64
        descricao:
          type: string
        estoque:
          type: number
          description: quantidade do produto em estoque
          format: double
        preco:
          type: number
          format: double
        categorias:
          type: array
          items:
            type: string
        detalhe:
          type: string
        tamanho:
          type: string
        imagens:
          type: array
          items:
            $ref: '#/components/schemas/Imagem'
      required: 
        - id
        - fornecedorId
        - descricao
        - preco
        - categorias
    Imagem:
      type: object
      properties:
        url:
          type: string
        caption:
          type: string
      required:
        - url
    ArrayDeFornecedores:
      type: array
      items:
        $ref: '#/components/schemas/Fornecedor'

  

paths:
  /fornecedores:
    get:
      tags:
      - fornecedores
      summary: Retorna todos fornecedores
    post:
      tags:
      - fornecedores
      summary: Cria um novo fornecedor
      responses:
        '200':
          description: OK
          content:
            application/json:
              
              #schema:
              #  $ref: '#/components/schemas/ArrayDeFornecedores'
                
  /fornecedores/{fornecedorId}:
    get:
      tags:
      - fornecedores
      summary: Retorna um fornecedor específico
      parameters:
        - $ref: '#/components/parameters/fornecedorId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
    put:
      tags:
      - fornecedores
      summary: Atualiza propriedade em um fornecedor
      parameters: 
        - $ref: '#/components/parameters/fornecedorId'
  /fornecedores/{fornecedorId}/produtos:
    post:
      tags:
      - fornecedores
      summary: Insere um produto
      parameters: 
        fornecedorId
  

