openapi: 3.0.1
info:
  title: Fornecedores API
  description: XXXXXXXXXXX
  contact:
    email: bcem@pucminas.br
  version: 1.0.0
externalDocs:
  description: Encontre mais a respeito da API Fornecedores
  url: https://github.com/caiosduarte/aws-montagem-exibicao-catalogo
servers:
- url: https://localhost:8080/catalogo/v1
- url: http://localhost:8080/catalogo/v1
tags:
- name: fornecedores
  description: Busca dos produtos em fornecedores.
components:
  schemas:
    Fornecedor:
      type: object
      properties:
        id:
          type: integer
          format: int32
        razaoSocial:
          type: string
        nomeFantasia:
          type: string
        cnpj:
          type: string
        status:
          type: string
          description: Status do Fornecedor
          enum:
          - ativo
          - inativo
        site:
          type: string
      required:
        - id
        - razaoSocial
        - nomeFantasia
        - cnpj
        - site
    Produto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: identificador interno do produto
        referencia:
          type: string
          description: referência do fabricante do produto
        fornecedorId:
          type: integer
          format: int32
          description: identificador do fornecedor do produto
        codigoNoFornecedor:
          type: string
          description: identificador do produto no fornecedor
        descricao:
          type: string
        estoque:
          type: number
          format: double
          description: quantidade do produto em estoque
        preco:
          type: number
          format: double
        categorias:
          type: array
          items:
            type: string
          description: categorias do produto
          example: ['informática', 'hardware', 'processadores']
        detalhe:
          type: string
          description: características detalhadas do produto
        tamanho:
          type: string
        imagens:
          type: array
          items:
            $ref: '#/components/schemas/Imagem'
        url:
          type: string
      required: 
        - id
        - fornecedorId
        - codigoNoFornecedor
        - descricao
        - preco
        - categorias
        - url
    Imagem:
      type: object
      properties:
        url:
          type: string
        caption:
          type: string
      required:
        - url
    ArrayDeFornecedores:
      type: array
      items:
        $ref: '#/components/schemas/Fornecedor'
  parameters:
    fornecedorId: 
      in: path
      name: offset
      required: true
      schema:
        type: integer
        minimum: 1
      description: O identificador do fornecedor.
      example: 20
paths:
  /fornecedores:
    get:
      tags:
        - fornecedores
      summary: Retorna todos fornecedores
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/ArrayDeFornecedores'
    post:
      tags:
        - fornecedores
      summary: Cria um novo fornecedor
      responses:
        '201':  # retornar a localização
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayDeFornecedores'
        '403':
            description: 'erro nos parâmetros'
        '5XX':
            description: 'erro no servidor'
                
  /fornecedores/{fornecedorId}:
    get:
      tags:
        - fornecedores
      summary: Retorna um fornecedor específico
      parameters:
        - $ref: '#/components/parameters/fornecedorId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
    put:
      tags:
        - fornecedores
      summary: Atualiza propriedade em um fornecedor
      parameters: 
        - $ref: '#/components/parameters/fornecedorId'
      responses:
        '200': # retornar a localização
          description: fornecedor atualizado
        '404':
          description: fornecedor não encontrado
        
  /fornecedores/{fornecedorId}/produtos:
    get:
      tags:
        - fornecedores/produtos
      sumary: Retorna os produtos de um fornecedor
    post:
      tags:
        - fornecedores/produtos
      summary: Insere um produto
      parameters: 
        - $ref: '#/components/parameters/fornecedorId'
      responses:
        '201': # retornar a localização
          description: produto criado
        '403':
          description: produto já criado
    put:
      tags:
        - fornecedores/produtos
      summary: atualiza um produto
      parameters: 
        - $ref: '#/components/parameters/fornecedorId'
      responses:
        '200': # retornar a localização
          description: produto atualizado
        '403':
          description: produto já criado
