openapi: 3.0.1
info:
  title: Fornecedores API
  description: API para manipular os fornecedores e receber os produtos dos crawllers
  contact:
    email: bcem@pucminas.br
  version: 1.0.0
externalDocs:
  description: Encontre mais a respeito da API Fornecedores
  url: https://github.com/caiosduarte/aws-montagem-exibicao-catalogo
servers:
- url: https://localhost:8080/catalogo/v1
- url: http://localhost:8080/catalogo/v1
tags:
- name: fornecedores
  description: Busca dos produtos em fornecedores.
components:
  schemas:
    Fornecedor:
      type: object
      properties:
        id:
          type: integer
          format: int32
        razaoSocial:
          type: string
        nomeFantasia:
          type: string
        cnpj:
          type: string
          pattern: '^\d{14}$'
        status:
          type: string
          description: Status do Fornecedor
          enum:
          - ativo
          - inativo
        site:
          type: string
      required:
        - id
        - razaoSocial
        - nomeFantasia
        - cnpj
        - site
      example:
        id: 1
        razaoSocial: B2W - Companhia Digital
        nomeFantasia: Sumarino
        cnpj: '00776574000660'
        status: ativo
        site: https://www.submarino.com.br/
      
    Produto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador interno do Produto
        referencia:
          type: string
          description: Referência do fabricante do Produto
        fornecedorId:
          type: integer
          format: int32
          description: Identificador do fornecedor do Produto
        codigoNoFornecedor:
          type: string
          description: 'Identificador do Produto no Fornecedor'
        descricao:
          type: string
          minLength: 2
        marca:
          type: string
          minLength: 2
        estoque:
          type: number
          format: double
          description: Quantidade do Produto em estoque
        preco:
          type: number
          format: double
        categorias:
          type: array
          items:
            type: string
            description: Categorias do Produto
        detalhes:
          type: object
          additionalProperties: {}
          description: 'Características detalhadas do produto: peso, tamanho, polegadas, acessórios, etc. (free-form object)'
        tamanho:
          type: string
        imagens:
          type: array
          items:
            $ref: '#/components/schemas/Imagem'
        url:
          type: string
          format: uri
      required: 
        - id
        - fornecedorId
        - codigoNoFornecedor
        - descricao
        - marca
        - preco
        - categorias
        - url
      example:
        id: 1
        referencia: M280-2V 
        fornecedorId: 1
        codigoNoFornecedor: 39ab
        descricao: 'Mouse Logitech M280 sem Fio - Preto'
        marca: Logitech
        estoque: 10
        preco: 200.99
        categorias: ['informática', 'periféricos', mouse, 'mouse óptico', mouse sem fio]
        detalhes: {texto: 'Mouse óptico sem fio preto garantia de 30 meses', cor: 'Preto', codigoDeBarras: 0097855107435, tamanho: '9x15x6cm'}
        url: https://www.submarino.com.br/produto/121960403/
    Imagem:
      type: object
      properties:
        url:
          type: string
          format: uri
        legenda:
          type: string
      required:
        - url
    ArrayDeFornecedores:
      type: array
      items:
        $ref: '#/components/schemas/Fornecedor'
    Erro:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message        
        
  parameters:
    fornecedor: 
      in: path
      name: fornecedorId
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
      description: O identificador do fornecedor.
      example: 1
  responses:
    Invalido:
        description: ID especificado inválido (não é um número).
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Erro'
    NaoEncontrado:
        description: ID especificado não encontrado.   
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Erro'
    Inesperado:
      description: Erro inesperado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Erro'              
        
paths:
  /fornecedores:
    get:
      tags:
        - fornecedores
      summary: Retorna todos fornecedores
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/ArrayDeFornecedores'
        default:
          $ref: '#/components/responses/Inesperado'
        
    post:
      tags:
        - fornecedores
      summary: Cria um novo fornecedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
      responses:
        '201': 
          description: Fornecedor criado.
          headers:
            Location:
              schema:
                type: string
              description: Retorna o URI do fornecedor criado.        
        '403':
          description: Fornecedor já criado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'         
        default:
          $ref: '#/components/responses/Inesperado'
                
  /fornecedores/{fornecedorId}:
    get:
      tags:
        - fornecedores
      summary: Retorna um fornecedor
      parameters:
        - $ref: '#/components/parameters/fornecedor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        '400':
          $ref: '#/components/responses/Invalido'
        '404':
          $ref: '#/components/responses/NaoEncontrado'
        default:
          $ref: '#/components/responses/Inesperado'

    put:
      tags:
        - fornecedores
      summary: Atualiza um fornecedor
      parameters: 
        - $ref: '#/components/parameters/fornecedor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
      responses:
        '200': 
          description: Fornecedor atualizado.
        '400':
          $ref: '#/components/responses/Invalido'
        '404':
          $ref: '#/components/responses/NaoEncontrado'
        default:
          $ref: '#/components/responses/Inesperado'
        
  /fornecedores/{fornecedorId}/produtos:
    get:
      tags:
        - fornecedores/produtos
      summary: Retorna os produtos de um fornecedor
      parameters: 
        - $ref: '#/components/parameters/fornecedor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
        '400':
          $ref: '#/components/responses/Invalido'
        '404':
          $ref: '#/components/responses/NaoEncontrado'
        default:
          $ref: '#/components/responses/Inesperado'
                
    post:
      tags:
        - fornecedores/produtos
      summary: Insere um produto do fornecedor
      parameters: 
        - $ref: '#/components/parameters/fornecedor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
        
      responses:
        '201': 
          description: Produto do Fornecedor criado.
          headers:
            Location:
              schema:
                type: string
              description: Retorna o URI do produto.          
        '403':
          description: Produto do Fornecedor já criado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '400':
          $ref: '#/components/responses/Invalido'
        '404':
          $ref: '#/components/responses/NaoEncontrado'
        default:
          $ref: '#/components/responses/Inesperado'
    put:
      tags:
        - fornecedores/produtos
      summary: atualiza um produto
      parameters: 
        - $ref: '#/components/parameters/fornecedor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'        
      responses:
        '200':
          description: Produto do Fornecedor atualizado.
        '400':
          $ref: '#/components/responses/Invalido'
        '404':
          $ref: '#/components/responses/NaoEncontrado'
        default:
          $ref: '#/components/responses/Inesperado'
        
  /fornecedores/{fornecedorId}/produtos/{produtoId}:
    get:
      tags:
        - fornecedores/produtos
      summary: Retorna os produtos de um fornecedor
      parameters: 
        - $ref: '#/components/parameters/fornecedor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '400':
          $ref: '#/components/responses/Invalido'
        '404':
          $ref: '#/components/responses/NaoEncontrado'
        default:
          $ref: '#/components/responses/Inesperado'
  
